### PR TITLE
Added additional targets for Rogue One and others

### PR DESCRIPTION
**Pull request by NducTiOnomBi**
Added Fulcrum with Omi targets
Updated Admiral Raddus targets
Added Rogue One AdRad targets
Added new Ewok targets with Primaries
Added Starkiller targets with Primaries
Added Stormtrooper Iden targets

### CODE REVIEW

**Comment by pawee** [comment]
Maybe I'm missing something but why would you prefer protection over health for Admiral Raddus when the team under his lead has a lot of protection ups going which is based on health?

**Comment by NducTiOnomBi** [comment]
> Maybe I'm missing something but why would you prefer protection over health for Admiral Raddus when the team under his lead has a lot of protection ups going which is based on health?

Yes, Rogue One allies need extra health as I have given them, but Raddus needs the extra protection (e.g. fast tank) to protect Jyn because of the synergy between them.

**Comment by NducTiOnomBi** [comment]
I'd be happy to discuss over discord

**Comment by pawee** [comment]
Assuming the armor and resistance do not change, increasing protection over health usually lifts up effective health and makes it look good for tanky characters. But that 10 surplus will result in deduction in other stats so either health, speed or both might drop for AdRad.

I did a quick test on a few accounts and the health might drop up to 20k+. So I'm not sure if that's preferred considering his kit.

I'd also recommend checking out SWGOH GAC Leaderboard (https://swgoh.gg/gac/leaderboard/) and look at what the best players are using on their characters. Oftentimes it could be opposite to what listed in the popular 'Best Mods' section. (You could also test your presets with their accounts.)

BTW, I like the idea of having the primaries in the presets.

**Comment by NducTiOnomBi** [comment]
I had based this on my own AdRad experience and my primary alliances modding targets. After you initially raised the question, I compared it Fatal's modding template in HU, and both are in alignment. I just looked at the GAC leaderboard and I do see some who prefer health over protection, but a majority of those I spot checked did choose protection over health.

How about this instead, I will leave the PvP alone and create separate Health preferred and Protection preferred targets?

Regarding the primaries.... Thanks! I just wanted to start with a few I am familiar with, and some "fun" ones (e.g. ewoks 🤣). I'm planning to do more in the future.

**Review by grandivory — APPROVED** [review]
Thanks for working through the issues with pawee. I'll get this released tonight!

**Pull request merged**
