### PR TITLE
New target rollout

### PR DESCRIPTION
**Pull request by pawee**
New characters: Hondo, 0-0-0, BT-1, Sana Starros and Dr.Aphra.

### CODE REVIEW

**Comment by NducTiOnomBi** [comment]
Why do you want to remove potency from Boushh?

**Comment by pawee** [comment]
- At R7 she has 141% base potency plus 20% from her unique if under a Hutt Cartel leader and 25% more from Jabba's reward (R7 is becoming a standard now due to RotE)
- Most people put Jabba on defense and all the well known counters don't require her to have additional potency than she already has.
- Check GAC leaderboard, best players now mod her for damage. Also in the best mod section, offense primary has taken over potency for cross mod.

**Comment by MCW77** [comment]
You have some braces wrong with savage:
Should read:

```
    [
      new OptimizationPlan('PvP/Omicron', 100, 0, 0, 0, 0, 0, 10, 0, 0, 50, 0, 0, 0, true),
      new OptimizationPlan('Balanced', 50, 0, 100, 25, 25, 25, 25, 0, 25, 12.5, 12.5, 0, 0, true),
    ],
```

**Comment by pawee** [comment]
For Dash, it works both ways since people are gonna relic him up for the ship so he'll have plenty of CC. I'll fix Savage in a day or two also with some potency (5 or max 10) for Boushh for the peace of mind but let me test the number first. I might be able to add a template for the Reva mission too, so please wait a day or two.

**Comment by pawee** [comment]
Ok this is it. 

- Add small amount of potency to Bouhh.
- Fix Savage syntax.
- Add a Reva mission template with 8th Brother as recommended by QuigMaster (https://www.youtube.com/watch?v=heOqcG78DDU). I've tuned it on a dozen of accounts but people will probably need to make minor adjustments if the goals are not achieved. 
- Fix avatar frame for neutral characters.

**Review by grandivory — APPROVED** [review]

**Pull request merged**
