### PR TITLE
Improve scrolling performance on mobile devices

### PR DESCRIPTION
**Pull request by pawee**
This should fix stuttering or freezes when scrolling in mobile browsers.

### CODE REVIEW

**Comment by MCW77** [comment]
Haven't used 'will-change' so far and so might be wrong. But reading up on the topic i'm assuming your changes would make things worse. You're adding will-change: transform to 4 elements, that don't have a transform property. So you are reserving ressources for an event, that will never happen. Perhapse a will-change: scroll-position on the elements with scrollbars would help. Did you test this? Maybe the scrolling results in a transform of elements.

**Comment by pawee** [comment]
There are currently two causes that make GI freezes and stutters when scrolling on mobile. First are the repaints and this can be fixed by will-change: transform. You can turn on the paint flashing in DevTools and see the elements causing repaints are where I've this will-change on. Scroll-position will not get rid of repaints. I've tested both.

Read more:
https://www.afasterweb.com/2017/07/27/optimizing-repaints/ 
https://dev.opera.com/articles/css-will-change-property/

The second is the number of DOMs, this still affects the mod explorer where the number of nodes could reach up to tens of thousands when browsing without filter on. This though requires further clean up in the UI.

**Review by grandivory — CHANGES_REQUESTED** [review]
Based on a lot of reading about `will-change`, it looks like in order to use it effectively, you'd need to make sure that it's only used on elements that will actually change soon, is added shortly before they change, and is removed after (both articles you linked list the same rules). Adding it to all of these elements and leaving it there is likely to introduce more performance issues than it solves, especially to optimize for an experience that I don't officially support.

**Comment by pawee** [comment]
Too bad but the cautions against using will-change are understandable, I'm closing this then. This little trick does really give an instant boost to the performance on phones and tablets by a huge without changing the current layout of the GI.

I've made a quick demonstration with my phone here:
https://www.youtube.com/watch?v=ahDKeuuAjzQ

(I refreshed the page as the hint that will-change has been re-applied).

**Pull request closed without merging**
